# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ann He
tagline:          ''
description:      ''
url:              "https://annh3.github.io"
math_engine:      mathjax

author:
  name:           'Ann He'
  url:            https://twitter.com/annnnhe

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/annh3/annh3.github.io

# plugins
plugins:
  - jekyll-gist
