# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ann He
tagline:          ''
description:      ''
url:              http://annhe.xyz
baseurl:          /

author:
  name:           'Ann He'
  url:            https://twitter.com/annnnhe

paginate:         5

# Custom vars

github:
  repo:           https://github.com/annh3/annh3.github.io

# plugins
plugins:
  - jekyll-gist
